### ISSUE TITLE
Decay highlighted cells

### ISSUE THREAD

**Issue by planemad** [mapbox/mapbeat#16]
From a convo with @batpad, it would be really cool if active cells decayed slowly by fading out instead of the on/off effect currently. This would help get a better sense of active areas after a period of time.

cc @geohacker

**Comment by geohacker** [comment]
@planemad great idea. I'm wondering how this'd work with gl filters. @batpad you have thoughts?

**Comment by planemad** [comment]
If each cell in the layer had a value for the activity, it would be simple data driven styling. Would probably have to create a geojson layer and keep updating it?
