### ISSUE TITLE
XSS Vulnerability in OSM username display

### ISSUE THREAD

**Issue by batpad** [mapbox/mapbeat#17]
We are not sanitizing OSM usernames and a maliciously crafted OSM username could trigger an XSS.

cc @geohacker

**Comment by batpad** [comment]
These lines: https://github.com/mapbox/mapbeat/blob/mb-pages/js/tiles.js#L122

We need to sanitize both the `usernames` and `tags` before the `.html()` call.

**Comment by batpad** [comment]
Fixed in #18

**Comment by geohacker** [comment]
@batpad thank you so much for patching this. 🙇
